### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by kpimarianenko** [kpimarianenko/homepage#8]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by zayzevnetov** [comment]
## Early history
( * ) **23.12.1994** Becomes the chieftain of the Warsong clan
( * ) **14.02.1995** Golka gives birth to his son Garrosh
( * ) **03.06.1995** Leads raids on ogre lands
( * ) **30.08.1995** Grom is captured by the ogres

## Rise of the Horde
( * ) **12.09.1994** Grom was present at the Kosh'harg celebration in Nagrand
( * ) **02.10.1994** Grom opposed the leader of the Frostwolf clan to defend a new era of war and state and drank the blood of Mannoroth
( * ) **28.10.1994** Invaded Shattrath against draenei
( * ) **13.11.1994** Fought against Nobundo

## Beyond the Dark Portal
( * ) **09.12.1995** The Warsong clan was spared the defeats of the Second War since Gul'dan manipulated Grom into staying behind on Draenor
( * ) **14.07.1996** The Horde was defeated by the Alliance of Lordaeron
( * ) **20.12.1998** He alongside Kargath Bladefist were summoned to join the reformed Horde
( * ) **15.02.1999** Grom and Rexxar led the attack on Nethergarde Keep
( * ) **03.01.2000** He battled against the Alliance for the control of the Azerothian side of the Dark Portal

## Revitalization of the Horde
( * ) **02.12.2000** Grom and the Warsong clan were forced into hiding in the wilds of Lordaeron
( * ) **12.03.2001** Grom was forced to fight the demonic curse that had left him weakened and listless.
( * ) **11.04.2002** Grom met a young chieftain named Thrall

## Reign of Chaos
( * ) **03.06.2002** Grom was captured by Alliance forces until he was rescued by Thrall and his forces
( * ) **15.8.2002** Grom used Alliance ships to travel the horde

##  Invasion of Kalimdor
( * ) **19.09.2001** Grom and his Warsong clan were separated from Thrall's fleet and made landfall on Kalimdor
( * ) **21.11.2001** Grom could not contain his bloodlust and instigated attacks on the human encampments
( * ) **23.12.2001** The fight with the demigod Cenarius and the appearance of the Manoroth
( * ) **05.04.2002** By drinking the Blood of Mannoroth, the Warsong clan was once again susceptible to the vile pit lord's control

## Redemption and death
( * ) **11.05.2002** Thrall and Grom set out to hunt down Mannoroth and located the vile demon in what is now Demon Fall Canyon in Ashenvale
( * ) **12.05.2002** Grom charged Mannoroth and sank Gorehowl into his chest, shattering the breastplate and slicing through to the infernal heart of the demon.
( * ) **12.05.2002** Exhausted by the infernal flame of Manoroth Grom dies
