### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by kpimarianenko** [kpimarianenko/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by zayzevnetov** [comment]
**Abilities**
Luck: Kazuma has an extraordinarily high luck stat, so high that even Luna was surprised. However, she claims that its numerical value isn't really essential to an adventurer. The only person Kazuma has ever lost to in a game of rock-paper-scissors is Eris, the Goddess of Luck. During his gambling streak in the nation of Elroad, Kazuma was able to win enough money to temporarily put a casino out of business. Though frustrating and unpredictable in the short-run, most things end up turning out well for him, no matter how many times he makes the same mistakes.

His insensitive behavior towards his friends is inevitably forgiven or forgotten due to some random circumstance, rather than learning his lesson or apologizing to them.
He is usually accompanied by Aqua, whose luck stat is the lowest possible level.
Kazuma cannot win a game of chess against someone who is significantly more skilled than him.
Most of his attacks are critical hits, even his words.
In a bad situation, he can blindly reach into his bag and probably get the best possible item.
Intelligence: His statistical intelligence is decently high, likely the highest out of his entire party. In practical use, he is very cunning and sharp, often employing the usage of unorthodox tactics. This makes a powerful combination with his luck stat; his ideas tend to be good ones.

Steal: Steal is a skill that improves depending on one’s luck stat, which makes it a useful skill for Kazuma due to his high luck stat. This manifests in Kazuma stealing the most valuable item someone has on them, but if he is using ‘Steal’ on a woman, it usually results in Kazuma stealing their panties, to his enjoyment.

Bind (バインド): Uses rope or wire to trap an opponent. The stronger the material the more effective it is.

Lurk: A skill that makes the user difficult to detect. While not providing the same level of concealment as invisibility, it does allow Kazuma to move without being noticed.

Concealment: A superior version of the Lurk skill. This grants Kazuma invisibility for a very short span of time.

Escape: Allows user to make a quick getaway.

Farsight: Allows a user to see far into the distance. Also gives the user night vision.

Snipe: A skill that is dependent on one's luck stat. This gives Kazuma incredible accuracy when using a bow and arrow.

Cook: He learned the ability of cooking with the idea of having a calm life and even opening a restaurant if he had the chance, he used this ability to help in the Axis Cult festival, making several dishes from Japan to attract customers

Smithing: Kazuma uses his smithing ability to great effect by inventing products from Earth, such as dynamite, condoms, lighters, and kotatsu, and selling the intellectual properties of these products for profit, as well as repair armor made out of adamantite.

Drain Touch: A skill normally only processed by the undead, Kazuma learned this skill from Wiz and can use it to drain mana from others as well as give. It can only be used through direct contact and drains mana very quickly, so Kazuma is able to utilize this skill offensively in order to render opponents unable to move once they are drained of mana.

Elemental Magic: Kazuma is able to use Tinder, Create Earth, Create Water, Wind Breath, and Freeze. Normally, these are very weak and simple magic abilities, but Kazuma utilizes his intelligence to maximize the effectiveness of each skill. By combining Create Earth and Wind Breath, Kazuma is able to blow dirt into people’s eyes. Create Water is convenient for producing clean drinking water whenever Kazuma needs it, Tinder is great for starting fires and burning through ropes to escape, and Freeze is used in combination with Create Water to freeze the ground and make it slippery for his opponents and also just to keep Darkness at bay as well as a replacement for air conditioning during the hot summer months.

Lip Reading: As long as Kazuma can see someone's mouth he can understand what they are saying. It is often used in combination with his Farsight ability

**Equipment**
Katana: Kazuma's trusty sword Chunchunmaru (affectionately named by Megumin) is his main melee weapon. However, he often switches to his more powerful magical abilities when he can.

Bow & Arrow: Primarily used by Kazuma in combination with his Snipe skill. He has been known to attach hooks and rope to the end of his arrows.

Vanir Mask: The mask is a mass produced copy of Vanir's original mask, although it has a slightly different design. When worn under a moonlit night, the wearer's mana will increase, their metabolism will be enhanced, and their skin will have a silky luster. Kazuma uses this mask when working as a thief with Chris.

Mithril Alloy Rope: Special rope made from mithirl that Kazuma custom ordered. Has highest level of toughness and can even bind astral bodies. Not even Eris's silver dagger can cut it.

**Relatives**
